<?php
/**
 * @package WordPress
 * @subpackage Default_Theme
 */
?>
<?php
 global $wh_theme_2012;
 $init_title = $wh_theme_2012->init_page_title();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" <?php language_attributes(); ?>>

<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="<?php bloginfo('html_type'); ?>; charset=<?php bloginfo('charset'); ?>" />

<meta content="width=1024px;" name="viewport" />
<title><?php echo $init_title; //wp_title('|', true, 'right'); ?> <?php bloginfo('name'); ?></title>

<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="/2009common/where_2010.css" type="text/css" />

<link rel="stylesheet" type="text/css" href="<?php echo get_bloginfo('stylesheet_directory').'/where_2012.css'; ?>" />

<link rel="alternate" type="application/rss+xml" title="<?php bloginfo('name'); ?> RSS Feed" href="<?php bloginfo('rss2_url'); ?>" />
<link rel="alternate" type="application/atom+xml" title="<?php bloginfo('name'); ?> Atom Feed" href="<?php bloginfo('atom_url'); ?>" />
<link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script><!--sticky footer-->

<!-- Generated by OpenX 2.8.8 -->
<script type='text/javascript' src='http://ads.stjosephmedia.com/www/delivery/spcjs.php?id=3&amp;block=1'></script>

<!-- DFP ad tags -->
<?php

$section = 'section';
$section = get_the_category();
$section = $section[0]->cat_name;
$tag = 'tag';
$posttags = get_the_tags();
$count=0;
	if ($posttags) { foreach($posttags as $tag0) { $count++; if (1 == $count) { $tag = $tag0->name;}}}
$slug = 'slug';
$slug = $post->post_name;
$ishome='no';
	if ( is_home() ) { $ishome = 'yes'; $slug = 'slug'; $tag = 'tag'; $section = 'section';}
$issingle='no';
	if ( is_single() ) { $issingle = 'yes';}
	if ( is_page() ) { $issingle = 'yes'; $section = 'section';}
?>

<script type='text/javascript'>
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
(function() {
var gads = document.createElement('script');
gads.async = true;
gads.type = 'text/javascript';
var useSSL = 'https:' == document.location.protocol;
gads.src = (useSSL ? 'https:' : 'http:') + 
'//www.googletagservices.com/tag/js/gpt.js';
var node = document.getElementsByTagName('script')[0];
node.parentNode.insertBefore(gads, node);
})();
</script>

<script type='text/javascript'>
googletag.cmd.push(function() {
googletag.pubads().setTargeting('section-WH', '<?php echo sanitize_title_with_dashes($section); ?>');
googletag.pubads().setTargeting('tag', '<?php echo sanitize_title_with_dashes($tag); ?>');
googletag.pubads().setTargeting('slug', '<?php echo $slug; ?>');
googletag.pubads().setTargeting('ishome', '<?php echo $ishome; ?>');
googletag.pubads().setTargeting('issingle', '<?php echo $issingle; ?>');
googletag.defineSlot('/9527589/WH_BB_Lower', [300, 250], 'div-gpt-ad-1344539030881-0').addService(googletag.pubads());
googletag.defineSlot('/9527589/WH_BB_Upper', [300, 251], 'div-gpt-ad-1351624106561-0').addService(googletag.pubads());
googletag.defineSlot('/9527589/WH_Leaderboard', [728, 90], 'div-gpt-ad-1344539030881-2').addService(googletag.pubads());
googletag.pubads().enableSingleRequest();
googletag.enableServices();
});
</script>

<script type="text/javascript">

var today=new Date();

function show_diff(yr,mon,day){
    var target=new Date(yr,mon,day);
    if (today.getTime() <= target.getTime()) {
        //Set 1 day in milliseconds
        var one_day=1000*60*60*24;
        //Calculate difference btw the two dates, and convert to days
        document.write(Math.ceil((target.getTime()-today.getTime())/(one_day))+
        " day");
    } else {
        //do something else
    }
}
</script>

<!--Start navigation drop-down fix for IE-->	
<script type="text/javascript"><!--//--><![CDATA[//><!--
sfHover = function() {
	var sfEls = document.getElementById("main-nav").getElementsByTagName("LI");
	for (var i=0; i<sfEls.length; i++) {
		sfEls[i].onmouseover=function() {
			this.className+=" sfhover";
		}
		sfEls[i].onmouseout=function() {
			this.className=this.className.replace(new RegExp(" sfhover\\b"), "");
		}
	}
}
if (window.attachEvent) window.attachEvent("onload", sfHover);
//--><!]]></script>
<!--End navigation drop-down fix for IE-->

<script src="http://mint.where.ca/?js" type="text/javascript"></script>

<?php wp_head(); ?>

</head>
<!--[if IE 7]>
   <body class="IE7">
<![endif]-->
<!--[if gt IE 7]>
   <body class="IE">
<![endif]-->
<!--[if !IE]>>
   <body>
<![endif]-->

<!--Start div#sticky-footer-IE if using pop-up footer-->

<div id="top-header">
    <div class="container">
        <div class="leaderboard">
            <img src="/images/advertisement-text-horiz.gif"  alt="The item beside this text is an advertisement" class="ad-indicator-horiz" />
			<!-- WH_Leaderboard -->
			<div id='div-gpt-ad-1344539030881-2' style="width:728px;float:right;">
			<script type='text/javascript'>
			googletag.cmd.push(function() { googletag.display('div-gpt-ad-1344539030881-2'); });
			</script>
			</div>
        </div>
                  
        <?php //include 'weather.php'; ?>
            
    </div>
</div>

<div id="header">
    <div class="container">       
        <h1><a href="/">Where</a></h1>
        
        <ul id="main-nav">
             <li class="region-indicator">
                <span id="region-calgary"><a href="/alberta/calgary/"><label>Calgary</label></a></span>
                <span id="region-canadianrockies"><a href="/canadianrockies/"><label>Canadian Rockies</label></a></span>
                <span id="region-edmonton"><a href="/alberta/edmonton/"><label>Edmonton</label></a></span>
                <span id="region-halifax"><a href="/nova-scotia/halifax/"><label>Halifax</label></a></span>
                <span id="region-muskoka"><a href="/ontario/muskoka/"><label>Muskoka</label></a></span>
                <span id="region-ottawa"><a href="/ontario/ottawa/"><label>Ottawa</label></a></span>
                <span id="region-toronto"><a href="/ontario/toronto/"><label>Toronto</label></a></span>
                <span id="region-vancouver"><a href="/british-columbia/vancouver/"><label>Vancouver</label></a></span>
                <span id="region-victoria"><a href="/british-columbia/victoria/"><label>Victoria</label></a></span>
                <span id="region-whistler"><a href="/british-columbia/whistler/"><label>Whistler</label></a></span>
                <span id="region-winnipeg"><a href="/manitoba/winnipeg/"><label>Winnipeg</label></a></span>
            </li>
            <li><a href="/newsletter/">NEWSLETTER</a></li>
            <li><a href="/digital-editions/">DIGITAL EDITIONS</a></li>
            <li><a href="/contests/">CONTESTS</a></li>
            <li><a href="/deals/">DEALS</a></li>
        </ul>

        <div id="social">
            <a class="fb-icon" href="https://www.facebook.com/wherecanada" target="_blank">Facebook</a>
            <a class="twitter-icon" href="http://twitter.com/wherecanada" target="_blank">Twitter</a>
            <a class="rss-icon" href="/where-rss-feeds/">RSS</a>
            <a class="flickr-icon" href="http://www.flickr.com/groups/wherecanada/" target="_blank">flickr</a>
            <a class="last-item email-icon" href="mailto:online@where.ca">email</a>
        </div>
        
        <div id="search">
            <form action="<?php bloginfo('home'); ?>" method="get" name="form1" id="searchForm">
                <input class="text" name="s" onfocus="if(this.value=='SEARCH')this.value=''" onblur="if(this.value=='')this.value='SEARCH'" value="SEARCH" id="search_box" placeholder="SEARCH" type="search">
                <input type="submit" id="searchsubmit" name="Search" value="">
                <input id="dup_filter" type="hidden" name="filter" value="1"/>
            </form>
        </div>

    </div><!--end #header .container-->
</div><!--end #header-->

<div id="page"><!--start #page-->
